/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuis2pbo;
//import com.sun.jdi.connect.spi.Connection;
import java.util.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection; // Gunakan Connection dari java.sql
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dedyb
 */
public class KasirCafe extends javax.swing.JFrame {
    private static Connection koneksi;
    private DefaultTableModel model;
    /**
     * Creates new form KasirCafe
     */
    public KasirCafe() {
        model = new DefaultTableModel();
        initComponents();
        this.jTableItem.setModel(model);
        model.addColumn("No");
        model.addColumn("ID Menu");
        model.addColumn("Menu");
        model.addColumn("Harga");
        model.addColumn("Kategori");
        model.addColumn("QTY");
        model.addColumn("SubTotal");
    }
    
    public static void buka_koneksi() {
        if (koneksi == null) {
            try {
                // URL Koneksi ke database
                String url = "jdbc:mysql://localhost:3306/cafe_pbo";
                String user = "root"; // Username MySQL
                String password = ""; // Password MySQL
                
                // Muat Driver JDBC
                Class.forName("com.mysql.cj.jdbc.Driver");
                
                // Buat koneksi
                koneksi = DriverManager.getConnection(url, user, password);
                System.out.println("Koneksi berhasil!");

            } catch (SQLException e) {
                System.out.println("Error Membuat Koneksi: " + e.getMessage());
            } catch (ClassNotFoundException e) {
                System.out.println("Driver tidak ditemukan: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jLabelUkuran = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonTambahkanItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabelTotalBelanja = new javax.swing.JLabel();
        jButtonBayar = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jLabelKategori = new javax.swing.JLabel();
        jLabelOutputMenu = new javax.swing.JLabel();
        jLabelOutputHarga = new javax.swing.JLabel();
        jLabelOutputUkuran = new javax.swing.JLabel();
        jLabelOutputKategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRevenue = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Penjualan Cafe Istimewa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Item : ");

        jLabelMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMenu.setText("Menu     :");

        jTextFieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemActionPerformed(evt);
            }
        });

        jLabelUkuran.setText("Ukuran            :");

        jLabelHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHarga.setText("Harga        :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Qty : ");

        jTextFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total : ");

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotal.setText("Rp. 00");

        jButtonTambahkanItem.setText("Tambahkan Item");
        jButtonTambahkanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahkanItemActionPerformed(evt);
            }
        });

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Menu", "Menu", "Kategori", "QTY", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(jTableItem);

        jLabel9.setText("Total Belanja : ");

        jLabelTotalBelanja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalBelanja.setText("Rp. 00");

        jButtonBayar.setText("Bayar");
        jButtonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jLabelKategori.setText("Kategori          :");

        jLabelOutputMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelOutputMenu.setText("Menu");

        jLabelOutputHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelOutputHarga.setText("Harga");

        jLabelOutputUkuran.setText("Ukuran");

        jLabelOutputKategori.setText("Kategori");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTotal)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelMenu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelOutputMenu))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelUkuran)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelOutputUkuran))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelOutputHarga))
                                    .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelKategori)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelOutputKategori))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButtonTambahkanItem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalBelanja)
                        .addGap(213, 213, 213))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 46, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalBelanja)
                    .addComponent(jLabel9))
                .addGap(97, 97, 97))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTambahkanItem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMenu)
                                    .addComponent(jLabelOutputMenu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelUkuran)
                                    .addComponent(jLabelOutputUkuran))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelKategori)
                                    .addComponent(jLabelOutputKategori))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelHarga)
                                    .addComponent(jLabelOutputHarga))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotal)
                                    .addComponent(jLabel7))
                                .addGap(61, 61, 61)))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Items", jPanel3);

        jLabel11.setText("Daftar Menu");

        jLabel12.setText("Makanan : ");

        jLabel13.setText("Minuman :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(883, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addGap(143, 143, 143)
                .addComponent(jLabel13)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kategori", jPanel1);

        jTableRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Jumlah Transaksi", "Total Revenue"
            }
        ));
        jScrollPane2.setViewportView(jTableRevenue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Revenue", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Object[] tempMenu = new Object[7];
    private int tempNomor = 1;
    private double tempHarga = 0;
    private double totalHarga = 0;
    
    
    
    
    private void jButtonTambahkanItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahkanItemActionPerformed
        // TODO add your handling code here:
        //ditambai if stok habis
        int stok = 0;
        try {
            // Buka koneksi ke database
            buka_koneksi();

            // Membuat statement untuk eksekusi SQL
            Statement s = koneksi.createStatement();

            // Query untuk mendapatkan menu berdasarkan ID
            String sql = "SELECT stok FROM menu WHERE id = " + tempMenu[1];
            ResultSet r = s.executeQuery(sql);
            
            // Periksa apakah hasil query tidak kosong
            if (r.next()) { // Menggunakan r.next() untuk memindahkan pointer ke baris data pertama
                stok = r.getInt("stok");
            } else {
                // Jika ID tidak ditemukan, tampilkan pesan
                JOptionPane.showMessageDialog(this, "Menu dengan ID " + tempMenu[1] + " tidak ditemukan.", "Info", JOptionPane.INFORMATION_MESSAGE);
            } 
            
            // Tutup result set dan statement
            r.close();
            s.close();
        } catch (SQLException e) {
            // Tampilkan pesan kesalahan jika terjadi masalah
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (stok >= (int)tempMenu[5]){
            tempMenu[0] = tempNomor;
            tempNomor = tempNomor + 1;
            totalHarga = totalHarga + (double)tempMenu[6];
            model.addRow(tempMenu);
            jLabelTotalBelanja.setText(String.valueOf(totalHarga));
            tempHarga = 0; 
        } else if (stok == 0){  
            JOptionPane.showMessageDialog(this, "Menu " + tempMenu[2] +" Sudah Habis", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Menu " + tempMenu[2] +" hanya tersisa " + stok, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonTambahkanItemActionPerformed

    private void jTextFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtyActionPerformed
        // TODO add your handling code here:
        String inQty = jTextFieldQty.getText();
        try {
            int qty = Integer.parseInt(inQty); 

            // Retrieve the boolean value from the label text
            double total = tempHarga * qty;
            
            jLabelTotal.setText(String.valueOf(total));
            tempMenu[5] = qty;
            tempMenu[6] = total;
        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid number
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldQtyActionPerformed

    private void jButtonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarActionPerformed
        // TODO add your handling code here:
        try {
            // Buka koneksi ke database
            buka_koneksi();

            // Membuat statement untuk eksekusi SQL
            Statement s = koneksi.createStatement();

            // Query untuk menambahkan data penjualan
            String sql = "INSERT INTO penjualan (tanggal) VALUES (NOW())";
            s.executeUpdate(sql);  // Gunakan executeUpdate() untuk INSERT

            // Mendapatkan ID penjualan terakhir yang baru saja dimasukkan
            ResultSet rs = s.executeQuery("SELECT LAST_INSERT_ID()");
            rs.next();
            int idPenjualan = rs.getInt(1); // Mendapatkan ID penjualan terakhir

            // Mengambil jumlah baris dan kolom dari model
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();

            // Membuat array 2 dimensi untuk menampung data tabel
            Object[][] tableData = new Object[rowCount][columnCount];
            for (int row = 0; row < rowCount; row++) {
                for (int col = 0; col < columnCount; col++) {
                    tableData[row][col] = model.getValueAt(row, col);
                }
            }

            // Loop untuk memasukkan data detail penjualan
            for (int row = 0; row < rowCount; row++) {
                String sqlDetail = "INSERT INTO detail_penjualan (id_penjualan, id_menu, harga_menu, qty, total_harga) " +
                        "VALUES (" + idPenjualan + ", " + tableData[row][1] + ", " + tableData[row][3] + ", " + tableData[row][5] + ", " + (Double.parseDouble(tableData[row][3].toString()) * Integer.parseInt(tableData[row][5].toString())) + ")";
                s.executeUpdate(sqlDetail); // Gunakan executeUpdate() untuk INSERT
                String sqlStok = "UPDATE menu SET stok = stok - " + tableData[row][5] + " WHERE id = " + tableData[row][1];
                s.executeUpdate(sqlStok);
            }

            // Tutup result set dan statement
            rs.close();
            s.close();
            tempNomor = 1;
            model.setRowCount(0);
            jLabelOutputMenu.setText("");
            jLabelOutputKategori.setText("");
            jLabelOutputUkuran.setText("");
            jLabelOutputHarga.setText("");
            jLabelTotal.setText("");
            jTextFieldItem.setText("");
            jTextFieldQty.setText("");
            
            JOptionPane.showMessageDialog(this, "Sudah Dibayar", "Informasi", JOptionPane.INFORMATION_MESSAGE);            
        } catch (SQLException e) {
            // Tampilkan pesan kesalahan jika terjadi masalah
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButtonBayarActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        totalHarga = 0;
        tempNomor = 1;
        jLabelTotalBelanja.setText(String.valueOf(totalHarga));

    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
        String idText = jTextFieldItem.getText();
    
        try {
            // Konversi teks menjadi integer (asumsi ID adalah integer)
            int id = Integer.parseInt(idText);

            // Panggil fungsi getMenu dengan parameter id
            getMenu(id);
        } catch (NumberFormatException e) {
            // Tampilkan pesan jika input bukan angka
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldItemActionPerformed
    
    
    private void getMenu(int id){
        try {
            // Buka koneksi ke database
            buka_koneksi();

            // Membuat statement untuk eksekusi SQL
            Statement s = koneksi.createStatement();

            // Query untuk mendapatkan menu berdasarkan ID
            String sql = "SELECT b.id AS id_menu, b.nama_menu, b.ukuran, b.harga, b.stok, k.nama AS kategori "
                    + "FROM menu b JOIN  kategori k ON b.kategori_id = k.id WHERE b.id = " + id;
            ResultSet r = s.executeQuery(sql);

            // Periksa apakah hasil query tidak kosong
            if (r.next()) { // Menggunakan r.next() untuk memindahkan pointer ke baris data pertama
                jLabelOutputMenu.setText(r.getString("nama_menu"));
                jLabelOutputUkuran.setText(r.getString("ukuran"));
                jLabelOutputHarga.setText(r.getString("harga"));
                jLabelOutputKategori.setText(r.getString("kategori"));
                tempMenu[1] = r.getString("id_menu");
                tempMenu[2] = r.getString("nama_menu");
                tempMenu[3] = r.getString("harga");
                tempHarga = r.getDouble("harga");
                tempMenu[4] = r.getString("kategori");
            } else {
                // Jika ID tidak ditemukan, tampilkan pesan
                JOptionPane.showMessageDialog(this, "Menu dengan ID " + id + " tidak ditemukan.", "Info", JOptionPane.INFORMATION_MESSAGE);
                jLabelOutputMenu.setText("Nama menu: Tidak ditemukan");
                jLabelUkuran.setText("Ukuran: Tidak ditemukan");
            }

            // Tutup result set dan statement
            r.close();
            s.close();
        } catch (SQLException e) {
            // Tampilkan pesan kesalahan jika terjadi masalah
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        buka_koneksi();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonBayar;
    private javax.swing.JButton jButtonTambahkanItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelKategori;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelOutputHarga;
    private javax.swing.JLabel jLabelOutputKategori;
    private javax.swing.JLabel jLabelOutputMenu;
    private javax.swing.JLabel jLabelOutputUkuran;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalBelanja;
    private javax.swing.JLabel jLabelUkuran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTable jTableRevenue;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldQty;
    // End of variables declaration//GEN-END:variables
}
